const items = [
  // ── 스니커즈 (sneakers) ──────────────────────────────────────
  {
    itemKey: 1,
    title: "Nike Air Force 1 Low '07 White",
    korTitle: "나이키 에어포스 1 로우 '07 화이트",
    brand: "Nike",
    korBrandName: "나이키",
    launchPrice: 119000,
    color: "White/White",
    img: "/img/sneakers/nikeAirForce_1.webp, /img/sneakers/nikeAirForce_2.webp, /img/sneakers/nikeAirForce_3.webp",
    logo: "/img/nike.jpg",
    category: "sneakers",
    saved: 342,
    sizes: ["240","245","250","255","260","265","270","275","280","285"],
  },
  {
    itemKey: 2,
    title: "Adidas Samba OG",
    korTitle: "아디다스 삼바 OG",
    brand: "Adidas",
    korBrandName: "아디다스",
    launchPrice: 149000,
    color: "White/Black/Gum",
    img: "/img/sneakers/adidasSamba_1.webp",
    logo: "/img/adidas.jpg",
    category: "sneakers",
    saved: 289,
    sizes: ["240","245","250","255","260","265","270","275","280"],
  },
  {
    itemKey: 3,
    title: "Bape ABC Camo Sta Low",
    korTitle: "베이프 에이비씨 카모 스타 로우",
    brand: "Bape",
    korBrandName: "베이프",
    launchPrice: 380000,
    color: "Green Camo",
    img: "/img/sneakers/bapeABC.webp",
    logo: "/img/bape.jpg",
    category: "sneakers",
    saved: 203,
    sizes: ["250","255","260","265","270","275","280"],
  },
  {
    itemKey: 4,
    title: "Kapital 5G Denim Chukka",
    korTitle: "캐피탈 5G 데님 척카",
    brand: "Kapital",
    korBrandName: "캐피탈",
    launchPrice: 520000,
    color: "Indigo Blue",
    img: "/img/sneakers/kapital5G_1.webp, /img/sneakers/kapital5G_2.webp",
    logo: "/img/kapital.jpg",
    category: "sneakers",
    saved: 87,
    sizes: ["255","260","265","270","275","280"],
  },
  {
    itemKey: 5,
    title: "Stussy x Nike Air Force 1 Low '8 Ball'",
    korTitle: "스투시 x 나이키 에어포스 1 로우 '8 볼'",
    brand: "Stussy",
    korBrandName: "스투시",
    launchPrice: 350000,
    color: "Black/White",
    img: "/img/sneakers/stussy8ball_1.webp, /img/sneakers/stussy8ball_2.webp",
    logo: "/img/stussy.jpg",
    category: "sneakers",
    saved: 412,
    sizes: ["250","255","260","265","270","275","280"],
  },
  {
    itemKey: 6,
    title: "Supreme x MM6 Maison Margiela",
    korTitle: "슈프림 x MM6 메종 마르지엘라",
    brand: "Supreme",
    korBrandName: "슈프림",
    launchPrice: 680000,
    color: "White",
    img: "/img/sneakers/supremeMM6_1.webp, /img/sneakers/supremeMM6_2.webp",
    logo: "/img/supreme.jpg",
    category: "sneakers",
    saved: 315,
    sizes: ["250","255","260","265","270","275","280"],
  },
  // ── 신발 (shoes) ─────────────────────────────────────────────
  {
    itemKey: 7,
    title: "Adidas German Handball Spezial",
    korTitle: "아디다스 저먼 핸드볼 스페치알",
    brand: "Adidas",
    korBrandName: "아디다스",
    launchPrice: 179000,
    color: "White/Black",
    img: "/img/sneakers/adidasGerman.webp",
    logo: "/img/adidas.jpg",
    category: "shoes",
    saved: 156,
    sizes: ["240","245","250","255","260","265","270","275"],
  },
  {
    itemKey: 8,
    title: "Adidas Originals Beckenbauer",
    korTitle: "아디다스 오리지널스 베켄바우어",
    brand: "Adidas",
    korBrandName: "아디다스",
    launchPrice: 209000,
    color: "White/Navy",
    img: "/img/sneakers/adidasOriginalsBeckenbauer.webp",
    logo: "/img/adidas.jpg",
    category: "shoes",
    saved: 98,
    sizes: ["240","245","250","255","260","265","270"],
  },
  {
    itemKey: 9,
    title: "Nike Air Max 90",
    korTitle: "나이키 에어맥스 90",
    brand: "Nike",
    korBrandName: "나이키",
    launchPrice: 189000,
    color: "White/Black/Infrared",
    img: "/img/nikeairmax.webp, /img/nikeairmax2.webp, /img/nikeairmax3.webp",
    logo: "/img/nike.jpg",
    category: "shoes",
    saved: 278,
    sizes: ["240","245","250","255","260","265","270","275","280"],
  },
  {
    itemKey: 10,
    title: "Nike x Travis Scott Air Max 1",
    korTitle: "나이키 x 트래비스 스캇 에어맥스 1",
    brand: "Nike",
    korBrandName: "나이키",
    launchPrice: 980000,
    color: "Saturn Gold/Wheat",
    img: "/img/nikeairmaxtravi.webp, /img/nikeairmaxtravi2.webp, /img/nikeairmaxtravi3.webp",
    logo: "/img/nike.jpg",
    category: "shoes",
    saved: 567,
    sizes: ["255","260","265","270","275","280"],
  },
  {
    itemKey: 11,
    title: "New Balance 574",
    korTitle: "뉴발란스 574",
    brand: "Newbalance",
    korBrandName: "뉴발란스",
    launchPrice: 139000,
    color: "White/Grey",
    img: "/img/newbalance574.png, /img/newbalance5742.png",
    logo: "/img/newbalance.jpg",
    category: "shoes",
    saved: 190,
    sizes: ["240","245","250","255","260","265","270","275","280"],
  },
  {
    itemKey: 12,
    title: "New Balance 574 Navy",
    korTitle: "뉴발란스 574 네이비",
    brand: "Newbalance",
    korBrandName: "뉴발란스",
    launchPrice: 159000,
    color: "Navy/White",
    img: "/img/newbalancenavy574.webp, /img/newbalancenavy.png, /img/newbalancenavy2.png",
    logo: "/img/newbalance.jpg",
    category: "shoes",
    saved: 145,
    sizes: ["240","245","250","255","260","265","270","275"],
  },
  {
    itemKey: 13,
    title: "Adidas Ultraboost 22",
    korTitle: "아디다스 울트라부스트 22",
    brand: "Adidas",
    korBrandName: "아디다스",
    launchPrice: 239000,
    color: "Core Black",
    img: "/img/adidasultra.webp",
    logo: "/img/adidas.jpg",
    category: "shoes",
    saved: 167,
    sizes: ["250","255","260","265","270","275","280","285"],
  },
  // ── 아우터 (outer) ────────────────────────────────────────────
  {
    itemKey: 14,
    title: "Carhartt WIP Unlined Duck Active Jacket",
    korTitle: "칼하트 WIP 언라인드 덕 액티브 재킷",
    brand: "Carhartt",
    korBrandName: "칼하트",
    launchPrice: 228000,
    color: "Hamilton Brown",
    img: "/img/outer/carharttWIPUnlined_1.webp, /img/outer/carharttWIPUnlined_2.webp",
    logo: "/img/carhartt.jpg",
    category: "outer",
    saved: 134,
    sizes: ["XS","S","M","L","XL","XXL"],
  },
  {
    itemKey: 15,
    title: "Stussy x Levi's Reversible Sherpa Jacket",
    korTitle: "스투시 x 리바이스 리버서블 쉐르파 재킷",
    brand: "Stussy",
    korBrandName: "스투시",
    launchPrice: 450000,
    color: "Blue Denim/White",
    img: "/img/outer/stussyxlevi's_1.webp, /img/outer/stussyxlevi's_2.webp",
    logo: "/img/stussy.jpg",
    category: "outer",
    saved: 256,
    sizes: ["XS","S","M","L","XL"],
  },
  {
    itemKey: 16,
    title: "Adidas Originals Beckenbauer Track Top",
    korTitle: "아디다스 오리지널스 베켄바우어 트랙 탑",
    brand: "Adidas",
    korBrandName: "아디다스",
    launchPrice: 189000,
    color: "White/Navy",
    img: "/img/outer/adidasOriginalsBeckenbauer.webp",
    logo: "/img/adidas.jpg",
    category: "outer",
    saved: 78,
    sizes: ["XS","S","M","L","XL","XXL"],
  },
  // ── 상의 (top) ────────────────────────────────────────────────
  {
    itemKey: 17,
    title: "IAB Studio Corduroy Overshirt",
    korTitle: "아이앱 스튜디오 코듀로이 오버셔츠",
    brand: "IABStudio",
    korBrandName: "아이앱 스튜디오",
    launchPrice: 190000,
    color: "Brown",
    img: "/img/outer/iabstudioCorduroy_1.webp, /img/outer/iabstudioCorduroy_2.webp",
    logo: "/img/IAB_Studio.jpg",
    category: "top",
    saved: 112,
    sizes: ["S","M","L","XL"],
  },
  {
    itemKey: 18,
    title: "Nike NSW Solo Swoosh Tee",
    korTitle: "나이키 NSW 솔로 스우시 티셔츠",
    brand: "Nike",
    korBrandName: "나이키",
    launchPrice: 89000,
    color: "Black",
    img: "/img/outer/nikeNswSolo_1.webp, /img/outer/nikeNswSolo_2.webp",
    logo: "/img/nike.jpg",
    category: "top",
    saved: 198,
    sizes: ["XS","S","M","L","XL","XXL"],
  },
  // ── 하의 (bottom) ─────────────────────────────────────────────
  {
    itemKey: 19,
    title: "Adidas Terry Shorts",
    korTitle: "아디다스 테리 쇼츠",
    brand: "Adidas",
    korBrandName: "아디다스",
    launchPrice: 79000,
    color: "Black",
    img: "/img/bottom/adidasTerryShorts.webp",
    logo: "/img/adidas.jpg",
    category: "bottom",
    saved: 89,
    sizes: ["XS","S","M","L","XL","XXL"],
  },
  {
    itemKey: 20,
    title: "Kapital Denim Mexican Pant",
    korTitle: "캐피탈 데님 멕시칸 팬츠",
    brand: "Kapital",
    korBrandName: "캐피탈",
    launchPrice: 680000,
    color: "Indigo",
    img: "/img/bottom/kapitalDenimMexican_1.webp, /img/bottom/kapitalDenimMexican_2.webp",
    logo: "/img/kapital.jpg",
    category: "bottom",
    saved: 134,
    sizes: ["S","M","L","XL"],
  },
  {
    itemKey: 21,
    title: "Nike Solo Swoosh Fleece Pants",
    korTitle: "나이키 솔로 스우시 플리스 팬츠",
    brand: "Nike",
    korBrandName: "나이키",
    launchPrice: 139000,
    color: "Dark Grey Heather",
    img: "/img/bottom/nikeSoloSwoosh_1.webp, /img/bottom/nikeSoloSwoosh_2.webp",
    logo: "/img/nike.jpg",
    category: "bottom",
    saved: 156,
    sizes: ["XS","S","M","L","XL","XXL"],
  },
  {
    itemKey: 22,
    title: "Stussy Surplus Cargo Pant",
    korTitle: "스투시 서플러스 카고 팬츠",
    brand: "Stussy",
    korBrandName: "스투시",
    launchPrice: 178000,
    color: "Olive",
    img: "/img/bottom/stussySurplusCargo_1.webp, /img/bottom/stussySurplusCargo_2.webp",
    logo: "/img/stussy.jpg",
    category: "bottom",
    saved: 203,
    sizes: ["XS","S","M","L","XL"],
  },
  {
    itemKey: 23,
    title: "Supreme Spellout Sweatpant",
    korTitle: "슈프림 스펠아웃 스웨트팬츠",
    brand: "Supreme",
    korBrandName: "슈프림",
    launchPrice: 280000,
    color: "Black",
    img: "/img/bottom/supremeSpellout_1.webp, /img/bottom/supremeSpellout_2.webp",
    logo: "/img/supreme.jpg",
    category: "bottom",
    saved: 178,
    sizes: ["XS","S","M","L","XL"],
  },
  // ── 모자 (headwear) ───────────────────────────────────────────
  {
    itemKey: 24,
    title: "IAB Studio Logo Beanie",
    korTitle: "아이앱 스튜디오 로고 비니",
    brand: "IABStudio",
    korBrandName: "아이앱 스튜디오",
    launchPrice: 89000,
    color: "Black",
    img: "/img/cap/IABStudioBeanie_1.webp, /img/cap/IABStudioBeanie_2.webp",
    logo: "/img/IAB_Studio.jpg",
    category: "headwear",
    saved: 76,
    sizes: ["FREE"],
  },
  {
    itemKey: 25,
    title: "Stussy Low Pro Stock Cap",
    korTitle: "스투시 로우 프로 스탁 캡",
    brand: "Stussy",
    korBrandName: "스투시",
    launchPrice: 79000,
    color: "Black",
    img: "/img/cap/stussyLow_1.webp, /img/cap/stussyLow_2.webp, /img/cap/stussyLow_3.webp",
    logo: "/img/stussy.jpg",
    category: "headwear",
    saved: 143,
    sizes: ["FREE"],
  },
  {
    itemKey: 26,
    title: "Supreme Washed Chino Twill Camp Cap",
    korTitle: "슈프림 워시드 치노 트윌 캠프 캡",
    brand: "Supreme",
    korBrandName: "슈프림",
    launchPrice: 120000,
    color: "Natural",
    img: "/img/cap/supremeWashed_1.webp, /img/cap/supremeWashed_2.webp",
    logo: "/img/supreme.jpg",
    category: "headwear",
    saved: 167,
    sizes: ["FREE"],
  },
  // ── 가방 (bag) ────────────────────────────────────────────────
  {
    itemKey: 27,
    title: "Bape Ape Head Shoulder Bag",
    korTitle: "베이프 에이프 헤드 숄더 백",
    brand: "Bape",
    korBrandName: "베이프",
    launchPrice: 280000,
    color: "Black",
    img: "/img/bag/BAPEApeHead_1.webp, /img/bag/BAPEApeHead_2.webp",
    logo: "/img/bape.jpg",
    category: "bag",
    saved: 112,
    sizes: ["FREE"],
  },
  {
    itemKey: 28,
    title: "Carhartt WIP Kickflip Backpack",
    korTitle: "칼하트 WIP 킥플립 백팩",
    brand: "Carhartt",
    korBrandName: "칼하트",
    launchPrice: 198000,
    color: "Black",
    img: "/img/bag/CarharttWIPKickflip_1.webp, /img/bag/CarharttWIPKickflip_2.webp",
    logo: "/img/carhartt.jpg",
    category: "bag",
    saved: 89,
    sizes: ["FREE"],
  },
  {
    itemKey: 29,
    title: "Supreme Backpack",
    korTitle: "슈프림 백팩",
    brand: "Supreme",
    korBrandName: "슈프림",
    launchPrice: 380000,
    color: "Black",
    img: "/img/bag/SupremeBackpack.webp",
    logo: "/img/supreme.jpg",
    category: "bag",
    saved: 234,
    sizes: ["FREE"],
  },
];

const mockUser = {
  user_id: 1,
  email: "demo@scream.kr",
  name: "스크림 유저",
  nickname: "sneakerhead",
  phoneNumber: "010-1234-5678",
  profileImage: "https://img.freepik.com/premium-vector/account-icon-user-icon-vector-graphics_292645-552.jpg",
  address: "서울시 강남구 테헤란로 123",
  bankName: "신한은행",
  accountNum: "110-123-456789",
  accountOwner: "스크림 유저",
};

const mockDeals = [
  {
    dealKey: 1,
    itemKey: 10,
    userId: 1,
    deal: "판매",
    itemTitle: "Nike x Travis Scott Air Max 1",
    size: "265",
    description: "정품 보증, 미착용 새상품입니다.",
    price: 1200000,
    totalPrice: 1212000,
    fee: 12000,
    deadline: "2026-04-30T00:00:00.000Z",
    sign: null,
    status: "대기중",
  },
  {
    dealKey: 2,
    itemKey: 5,
    userId: 1,
    deal: "구매",
    itemTitle: "Stussy x Nike Air Force 1 Low '8 Ball'",
    size: "270",
    description: "최대한 빠른 거래 희망합니다.",
    price: 420000,
    totalPrice: 424200,
    fee: 4200,
    deadline: "2026-04-15T00:00:00.000Z",
    sign: null,
    status: "대기중",
  },
  {
    dealKey: 3,
    itemKey: 1,
    userId: 1,
    deal: "판매",
    itemTitle: "Nike Air Force 1 Low '07 White",
    size: "260",
    description: "한 번 착용한 상품입니다. 상태 최상.",
    price: 145000,
    totalPrice: 146450,
    fee: 1450,
    deadline: "2026-05-01T00:00:00.000Z",
    sign: null,
    status: "완료",
  },
];

const mockWishlist = [
  { wishKey: 1, user_id: 1, itemKey: 1 },
  { wishKey: 2, user_id: 1, itemKey: 10 },
  { wishKey: 3, user_id: 1, itemKey: 6 },
];

const mockReviews = [
  {
    reviewKey: 1,
    user_id: "streetwear_kim",
    content: "#나이키 #에어포스1 #데일리룩 오늘 신발 너무 마음에 들어요",
    img: "/img/sneakers/nikeAirForce_1.webp",
    itemKey: 1,
    review: true,
  },
  {
    reviewKey: 2,
    user_id: "sneaker_park",
    content: "아디다스 삼바 👟 역시 명작이다",
    img: "/img/sneakers/adidasSamba_1.webp",
    itemKey: 2,
    review: true,
  },
  {
    reviewKey: 3,
    user_id: "hypebeast_lee",
    content: "#슈프림 #MM6 이 조합 미쳤다",
    img: "/img/sneakers/supremeMM6_1.webp",
    itemKey: 6,
    review: true,
  },
  {
    reviewKey: 4,
    user_id: "streetwear_choi",
    content: "칼하트 재킷 퀄리티 실화냐 🔥",
    img: "/img/outer/carharttWIPUnlined_1.webp",
    itemKey: 14,
    review: true,
  },
  {
    reviewKey: 5,
    user_id: "kfashion_jung",
    content: "스투시 카고 팬츠 핏 미쳐버림 #스트리트웨어",
    img: "/img/bottom/stussySurplusCargo_1.webp",
    itemKey: 22,
    review: true,
  },
  {
    reviewKey: 6,
    user_id: "sneakerhead_oh",
    content: "트래비스 스캇 x 나이키 드림 신발 💛 #트래비스스캇",
    img: "/img/nikeairmaxtravi.webp",
    itemKey: 10,
    review: true,
  },
];

const MOCK_TOKEN = "mock_access_token_scream_2026";

module.exports = { items, mockUser, mockDeals, mockWishlist, mockReviews, MOCK_TOKEN };
